# Generated by Django 3.1.4 on 2021-02-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5, unique=True)),
                ('companyName', models.CharField(max_length=200)),
                ('latestPrice', models.FloatField()),
                ('change', models.FloatField()),
                ('changePercent', models.FloatField()),
                ('extendedPrice', models.FloatField()),
                ('extendedChange', models.FloatField()),
                ('extendedChangePercent', models.FloatField()),
                ('open', models.FloatField()),
                ('peRatio', models.FloatField()),
                ('latestVolume', models.FloatField()),
                ('marketCap', models.FloatField()),
                ('week52High', models.FloatField()),
                ('week52Low', models.FloatField()),
                ('ytdChange', models.FloatField()),
            ],
        ),
    ]
