# Generated by Django 3.1.4 on 2021-02-07 10:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import stocks.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='change',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='changePercent',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='extendedChange',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='extendedChangePercent',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='extendedPrice',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='latestPrice',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='latestVolume',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='marketCap',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='open',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='peRatio',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='week52High',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='week52Low',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ytdChange',
        ),
        migrations.AddField(
            model_name='stock',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=stocks.models.SymbolField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$')]),
        ),
    ]
