# Generated by Django 3.1.4 on 2021-06-25 17:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import stocks.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0005_auto_20210226_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', stocks.models.SymbolField(max_length=5, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$')])),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transaction', models.CharField(max_length=5)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
